databases:
  - name: rentacar
    databaseName: rentacar
    user: efiamotu

services:
  - type: web
    name: rentacar
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rentacar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false